name: CI/CD Pipeline with Security Checks

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  security-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install security tools
        run: |
          pip install bandit safety pre-commit

      - name: Run Bandit security scan
        run: |
          bandit -r . -f json -o bandit-report.json || true
          bandit -r . || true

      - name: Run Safety dependency check
        run: |
          safety check --json --output safety-report.json || true
          safety check || true

      - name: Run pre-commit hooks
        run: |
          pre-commit install
          pre-commit run --all-files || true

      - name: Run tests
        run: |
          python -m pytest tests/ -v || true

      - name: Upload security reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json

  build-docs:
    runs-on: ubuntu-latest
    needs: security-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: |
          mkdocs build

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site/
