name: Validate Contributions

on:
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate JSON files
      run: |
        for file in $(find . -name '*.json'); do
          jq . $file > /dev/null || (echo "Invalid JSON in $file" && exit 1)
        done

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        args: './**/*.md'
